name: c004_covid19_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: false
  assets:
    - assets/